# Generated by Django 5.0.6 on 2024-05-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='doneORnot',
        ),
        migrations.DeleteModel(
            name='Completed',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
