# Generated by Django 5.0.6 on 2024-06-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0008_remove_task_done_delete_completed_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcoes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=200)),
                ('data', models.DateField()),
                ('feita', models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to='tasks.completed')),
            ],
        ),
    ]
